version: "3"
services:
  api:
    build: .
    image: bug-viewer
    ports:
      - "443:4443"
      - "80:8080"
    environment:
      - SESSION_SECRET=Secret
      - ORIGIN=https://...
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
