---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugviewer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: leandrolorenzini/bug-viewer:debug
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: SESSION_SECRET
          value: "123"
        - name: ORIGIN
          value: "https://localhost"

---
apiVersion: v1
kind: Service
metadata:
  name: bugviewer
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080