---
apiVersion: v1
kind: Service
metadata:
  name: bugviewer
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 4443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
