---
name: Security

on:
  workflow_dispatch:
  pull_request:
    branches: [main] #Replace with your protected branch name
  schedule:
    - cron: '0 0 * * MON'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run scanner
        env:
          BRANCH: main                            # Replace with your protected branch name
          SERVER: ${{ secrets.BUGVIEWER_SERVER }} # Your server address
          TOKEN:  ${{ secrets.BUGVIEWER_TOKEN }}  # Token is created using BugViewer's web interface
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
          FULL_CHECK: ${{github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'}}
        run: |
          curl -O ${{ secrets.BUGVIEWER_SERVER }}/scanner.tar.gz
          tar -xf scanner.tar.gz
          cd scanner && sh scanner.sh
